export const genresList = [
    {title:"Drama",slug:"drama"},
    {title:"Musik",slug:"musik"},
    {title:"Thriller",slug:"thriller"},
    {title:"Børne - Familiefilm",slug:"boerne-familiefilm"},
    {title:"Science fiction",slug:"science-fiction"},
    {title:"Komedie",slug:"komedie"},
    {title:"Action",slug:"action"},
    {title:"Western",slug:"western"},
    {title:"Adventure",slug:"adventure"},
    {title:"Walt Disney - Pixar",slug:"walt-disney"},
    {title:"Danske film",slug:"danske-film"},
    {title:"Gysere",slug:"gysere"},
    {title:"Romantik",slug:"romantik"},
    {title:"Vintage",slug:"vintage"},
    {title:"Agent 007",slug:"agent-007"},
    {title:"Krigsfilm",slug:"krigsfilm"},
    {title:"Dokumentar",slug:"dokumentar"},
    {title:"Krimi - Thriller",slug:"krimi-thriller"},
    {title:"Store Filmplakater",slug:"store-filmplakater"},
    {title:"Karatefilm",slug:"karatefilm"},
    {title:"Marvel - DC Comics",slug:"marvel-dc-comics"},
    {title:"Film Programmer",slug:"film-programmer"}
    ]